### ISSUE TITLE
Upgrade nuget packages for providers

### ISSUE THREAD

**Issue by juchom** [2020IP/TwentyTwenty.Storage#11]
Current package for IStorageProvider is 2.1

For Azure & LocalStorage package is 2.0.

The signature of the interface has change (CopyBlobAsync) which is not present in the 2.0 packages of implementations

**Comment by robertbaker** [comment]
I'm sad to see that this issue is almost a year old.

SemVer rules were violated, TwentyTwenty.Storage contained a breaking change. TwentyTwenty.Storage 2.1 is not usable if you need TwentyTwenty.Storage.Local.

**Comment by jarroda** [comment]
Fixed in version 2.4. All providers have been updated.
