### ISSUE TITLE
ListBlobs in LocalStorageProvider only returns files in current directory

### ISSUE THREAD

**Issue by mpahk** [2020IP/TwentyTwenty.Storage#13]
The current _LocalStorageProvider_ only returns files that are in current directory. Meaning that files in subdirectories are not returned.

A quick fix would be that in the method _ListBlobs_ you specify the _searchPattern_ and _searchOption_:
`var fileInfo = dirInfo.GetFiles("*", SearchOption.AllDirectories);`

**Comment by jarroda** [comment]
Would you mind submitting a pull request for that change?

**Comment by mpahk** [comment]
I wouldn't if you would upgrade the project. .xproj is deprecated.

**Comment by jarroda** [comment]
Fixed in version 2.4
