### ISSUE TITLE
GetBlobUrl in AmazonStorageProvider url invalid

### ISSUE THREAD

**Issue by Fabioh** [2020IP/TwentyTwenty.Storage#2]
I had a problem with the method "GetBlobUrl" in a instance of an object "AmazonStorageProvider", the generated url doesn't follows the AWS patterns like these:
- http://bucket.s3.amazonaws.com/path/to/your/file
- http://bucket.s3-aws-region.amazonaws.com/path/to/your/file
- http://s3-aws-region.amazonaws.com/bucket/path/to/your/file

Reference: [http://stackoverflow.com/questions/34993366/how-to-get-public-url-after-uploading-image-to-s3](http://stackoverflow.com/questions/34993366/how-to-get-public-url-after-uploading-image-to-s3)

Could you please verify this issue.

Best regards,
Fábio Henrique Gabriele

**Comment by jarroda** [comment]
I just tested this and it appears to be working correctly for me.  I generated a random blob in a random container (prefix in AWS speak) and `GetBlobUrl` returned 
> https://s3.amazonaws.com/2020-storage-test/storagetest-a637fa32b9474015903f71bcfe460e0f/fd5a92f7129c4a05ab37b35e773653cb
This appears to be a correctly formatted URL for this blob, and in fact does work.

The code for this is quite simple.  
```
public string GetBlobUrl(string containerName, string blobName)
{
    return $"{_serviceUrl}/{_bucket}/{GenerateKeyName(containerName, blobName)}";
}
```

Is your service url changed to something that is causing an invalid URL to be generated?

**Comment by jarroda** [comment]
Will reopen this if it is still an issue.
