### ISSUE TITLE
Upgrade Azure dependency

### ISSUE THREAD

**Issue by jnyrup** [2020IP/TwentyTwenty.Storage#29]
[WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage) is no longer updated, but split into several packages, where blob is now available in 
[Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob)

Does the Azure provider intend to use the new blob package as well?

**Comment by ericgreenmix** [comment]
Yeah, it would be great to get updated. Would you be interested in doing a PR with that change?

**Comment by jnyrup** [comment]
I'll give it a try

**Comment by jnyrup** [comment]
I won't have time at work to do this anyways.

For some who picks this up, note that Microsoft already released a another newer version of their storage SDK for Azure blobs.
https://www.nuget.org/packages/Azure.Storage.Blobs/

**Comment by ericgreenmix** [comment]
closed by #32
