### ISSUE TITLE
Error attempting to run DNX design time process

### ISSUE THREAD

**Issue by sohaibjaved44** [2020IP/TwentyTwenty.Storage#7]
Hi, I have just downloaded and opened in visual studio 2015, it started throwing this error.
![image](https://cloud.githubusercontent.com/assets/8418548/20355887/b9271c98-ac44-11e6-9245-92eb1ddddb85.png)

I have tried it with VS 2013 but its incompatiable with that.

So I opened new console application in VS 2015
then I installed nuget packages in the same order as below 
install-package TwentyTwenty.Storage
install-package TwentyTwenty.Storage.Azure
install-package TwentyTwenty.Storage.Local

All worked fine, except Local storage,   TwentyTwenty.Storage.Local when used in code exactly at this line 
IStorageProvider provider = new LocalStorageProvider(@"E:\projectA");
 started throw System.TypeLoadException ,

I'm sure about this line because there is no other line of code there.

It again works if I uninstall TwentyTwenty.Storage.Local nuget package or I remove this line of code 
IStorageProvider provider = new LocalStorageProvider(@"E:\projectA");

**Comment by jarroda** [comment]
Make sure you have the newest dotnet core bits installed.  The DNX related language in that error indicates to me you have out-of-date stuff installed.  
https://www.microsoft.com/net/download/core
Install the visual studio tooling in addition to the SDK.

**Comment by sohaibjaved44** [comment]
Great thanks let me update installed stuff.

**Comment by sohaibjaved44** [comment]
Hi I did exactly what you suggested, You were right my stuff was old so I updated VS 2015 then installed sdk and tooling as well, but still its throwing TypeLoadException.

I have latest nuget installed. and in my visual studio I have only

**Comment by sohaibjaved44** [comment]
Hey are you fixing this issue? As its coming up in the latest release only

**Comment by jarroda** [comment]
Try again with the new 2.0.0 packages I just pushed.

**Comment by sohaibjaved44** [comment]
Its working fine now with the latest release. Thanks.
